---
galaxy_info:
  role_name: python
  author: Fabien Taxil

  description: >-
    Install different versions of the python programing language

  license: MIT
  min_ansible_version: "2.8"

  platforms:
    - name: macOS
      versions:
        - all

  galaxy_tags:
    - python

dependencies:
  - role: homebrew
    when: ansible_os_family == 'Darwin'
