---
galaxy_info:
  role_name: dotfiles
  author: Fabien Taxil

  description: >-
    Install dotfiles under the $HOME directory

  license: MIT
  min_ansible_version: "2.8"

  platforms:
    - name: macOS
      versions:
        - all

  galaxy_tags:
    - configuration
    - dotfiles

dependencies:
  - role: workspace
