- name: mount | Install cifs utils
  ansible.builtin.apt:
    name: cifs-utils
    state: present

- name: mount | Copy the fstab file.
  ansible.builtin.template:
    src: fstab
    dest: /etc/fstab
    owner: root
    group: root
    mode: "0644"

- name: mount | Symlink drives in /
  ansible.builtin.file:
    src: /mnt/{{ item }}
    dest: /{{ item }}
    state: link
    owner: lixaft
    group: lixaft
    mode: "0755"
  loop:
    - c
    - n
    - o
    - y
    - z
