- name: resolv | Setup resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    create: true
    line: "{{ item }}"
    state: present
    owner: lixaft
    group: lixaft
    mode: "0644"
  loop:
    - nameserver 172.16.1.100
    - nameserver 192.168.2.254
