- name: Site
  hosts: workstation
  become: true
  become_user: root
  pre_tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
      tags:
        - update
  roles:
    - workstation
