- name: Workstation
  hosts: workstation
  become: true
  become_user: root
  environment:
    XDG_CACHE_HOME: "/home/lixaft/.cache"
    XDG_CONFIG_HOME: "/home/lixaft/.config"
    XDG_DATA_HOME: "/home/lixaft/.local/share"
    XDG_STATE_HOME: "/home/lixaft/.local/state"
  pre_tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
  roles:
    - workstation
