- name: Download brave gpg key
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /etc/apt/keyrings/brave-browser.gpg
    owner: root
    group: root
    mode: "0644"

- name: Add brave repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/brave-browser.gpg]
      https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present

- name: Install brave
  ansible.builtin.apt:
    name: brave-browser
  tags:
    - update
