- name: Download pip zipapp
  ansible.builtin.get_url:
    url: https://bootstrap.pypa.io/pip/pip.pyz
    dest: /tmp/pip.pyz
    owner: lixaft
    group: lixaft
    mode: "0644"

- name: Install qtile dependencies from APT
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - python3-cairocffi
    - python3-cffi
    - libpangocairo-1.0-0
    - python3-xcffib
    - xserver-xorg
  tags:
    - update

- name: Install qtile dependencies from pypi
  ansible.builtin.command:
    cmd: python3 /tmp/pip.pyz install -U {{ item }}
  loop:
    - psutil
  register: ret
  changed_when: '"Requirement already satisfied: " not in ret.stdout'
  tags:
    - update

- name: Install qtile from pypi
  ansible.builtin.command:
    cmd: python3 /tmp/pip.pyz install -U qtile
  register: ret
  changed_when: '"Requirement already satisfied: " not in ret.stdout'
  tags:
    - update

- name: Create the qtile desktop fille
  ansible.builtin.copy:
    src: qtile.desktop
    dest: /usr/share/xsessions/qtile.desktop
    owner: root
    group: root
    mode: "0644"
