- name: bazecor | Create install directory
  ansible.builtin.file:
    path: /home/lixaft/.opt/bazecor/{{ bazecor_version }}
    state: directory
    owner: lixaft
    group: lixaft
    mode: "0755"

- name: bazecor | Download app image
  ansible.builtin.get_url:
    url: https://github.com/Dygmalab/Bazecor/releases/download/v{{ bazecor_version }}/Bazecor-{{ bazecor_version }}-x64.AppImage
    dest: /home/lixaft/.opt/bazecor/{{ bazecor_version }}/bazecor
    owner: lixaft
    group: lixaft
    mode: "0755"

- name: bazecor | Symlink executable
  become: true
  become_user: lixaft
  ansible.builtin.file:
    src: /home/lixaft/.opt/bazecor/{{ bazecor_version }}/bazecor
    dest: /home/lixaft/.local/bin/bazecor
    state: link
    owner: lixaft
    group: lixaft

- name: bazecor | Copy desktop file
  ansible.builtin.copy:
    src: bazecor.desktop
    dest: /home/lixaft/.local/share/applications/bazecor.desktop
    force: true
    owner: lixaft
    group: lixaft
    mode: "0644"
