- name: Install rust binaries
  become: true
  become_user: lixaft
  environment:
    PATH: /home/lixaft/.cargo/bin:{{ ansible_env.PATH }}
  community.general.cargo:
    name: "{{ item }}"
    path: /home/lixaft/.local
    state: latest
  loop:
    - bottom
    - exa
    - procs
    - starship
  tags:
    - update
