- name: Clone dotfiles repository
  become: true
  become_user: lixaft
  ansible.builtin.git:
    repo: git@github.com:lixaft/dotfiles
    dest: /home/lixaft/dev/dotfiles
    update: false

- name: Symlink configuration files
  ansible.builtin.file:
    src: /home/lixaft/dev/dotfiles/src/{{ item }}
    dest: /home/lixaft/{{ item }}
    state: link
    force: true
    owner: lixaft
    group: lixaft
  loop:
    - .bashrc
    - .config/bat
    - .config/fish
    - .config/git
    - .config/nvim
    - .config/qtile
    - .config/rofi
    - .config/starship.toml
    - .config/tmux
    - .config/wezterm
    - .Xresources
    - .pdbrc
    - .pythonrc

- name: Symlink binary files
  ansible.builtin.file:
    src: /home/lixaft/dev/dotfiles/src/.local/bin/{{ item }}
    dest: /home/lixaft/.local/bin/{{ item }}
    state: link
    force: true
    owner: lixaft
    group: lixaft
  loop:
    - tmux-go
    - launcher
    - powermenu
