- name: Add fish repository
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3

- name: Install fish
  ansible.builtin.apt:
    name: fish
    state: latest
  tags:
    - update

- name: Setup fish as default shell
  ansible.builtin.user:
    name: lixaft
    shell: /usr/bin/fish
