- name: Add neovim repository
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present

- name: Install neovim
  ansible.builtin.apt:
    name: neovim
    state: latest
  tags:
    - update

- name: Clone lazy.nvim repository
  become: true
  become_user: lixaft
  ansible.builtin.git:
    repo: https://github.com/folke/lazy.nvim
    dest: /home/lixaft/.local/share/nvim/lazy/lazy.nvim
    version: stable
    update: true
  tags:
    - update
