- name: Install utilities
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - aptitude
    - bat
    - cmake
    - curl
    - dos2unix
    - fd-find
    - fzf
    - git
    - graphviz
    - htop
    - jq
    - less
    - make
    - neofetch
    - qemu-system-x86
    - ripgrep
    - software-properties-common
    - sqlite
    - tree
    - watch
    - wget
  tags:
    - update

- name: Symlink utility executables
  ansible.builtin.file:
    src: /usr/bin/{{ item.src }}
    dest: /home/lixaft/.local/bin/{{ item.dest }}
    state: link
    owner: lixaft
    group: lixaft
  loop:
    - src: fdfind
      dest: fd
    - src: batcat
      dest: bat

- name: Build bat cache
  ansible.builtin.command:
    cmd: batcat cache --build
  changed_when: true
