- name: Clone dotfiles repository
  become: true
  become_user: lixaft
  ansible.builtin.git:
    repo: git@github.com:lixaft/dotfiles
    dest: /home/lixaft/dotfiles
    update: false
    accept_newhostkey: true
  tags: &tags
    - dotfiles

- name: Delete configuration files
  become: true
  become_user: lixaft
  ansible.builtin.command:
    cmd: stow -D {{ item }}
    chdir: /home/lixaft/dotfiles
  loop: &stow
    - alacritty
    - bat
    - bin
    - fish
    - git
    - i3
    - nvim
    - python
    - sqlite
    - starship
    - tmux
  changed_when: true
  tags: *tags

- name: Stow configuration files
  become: true
  become_user: lixaft
  ansible.builtin.command:
    cmd: stow {{ item }}
    chdir: /home/lixaft/dotfiles
  loop: *stow
  changed_when: true
  tags: *tags

- name: Build bat cache
  become: true
  become_user: lixaft
  ansible.builtin.command:
    cmd: batcat cache --build
  changed_when: true
  tags: *tags
