- name: Install flatpack
  ansible.builtin.apt:
    name: flatpak
    state: latest
  tags: &tags
    - flatpak

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present
  tags: *tags
