- name: Download the go archive
  ansible.builtin.get_url:
    url: https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
    dest: /tmp/go{{ go_version }}.linux-amd64.tar.gz
    owner: lixaft
    group: lixaft
    mode: "0755"
  tags: &tags
    - go

- name: Create go unarchive directory
  ansible.builtin.file:
    path: /tmp/go{{ go_version }}.linux-amd64
    state: directory
    owner: lixaft
    group: lixaft
    mode: "0755"
  tags: *tags

- name: Unarchive go
  ansible.builtin.unarchive:
    src: /tmp/go{{ go_version }}.linux-amd64.tar.gz
    dest: /tmp/go{{ go_version }}.linux-amd64
    owner: lixaft
    group: lixaft
    mode: "0755"
  tags: *tags

- name: Create go directory
  ansible.builtin.file:
    path: /home/lixaft/.opt/go
    state: directory
    owner: lixaft
    group: lixaft
    mode: "0755"
  tags: *tags

- name: Move go directory
  ansible.builtin.command:
    argv:
      - mv
      - /tmp/go{{ go_version }}.linux-amd64/go
      - /home/lixaft/.opt/go/{{ go_version }}
    creates: /home/lixaft/.opt/go/{{ go_version }}
  tags: *tags

- name: Symlink go executables
  ansible.builtin.file:
    src: /home/lixaft/.opt/go/{{ go_version }}/bin/{{ item }}
    dest: /home/lixaft/.local/bin/{{ item }}
    state: link
    owner: lixaft
    group: lixaft
  loop:
    - go
    - gofmt
  tags: *tags
