- name: Download MongoDB GPG key
  ansible.builtin.get_url:
    url: https://pgp.mongodb.com/server-7.0.asc
    dest: /etc/apt/keyrings/mongodb.asc
    owner: root
    group: root
    mode: "644"
  tags: &tags
    - apps
    - mongo
    - mongodb

- name: Add MongoDB repository
  ansible.builtin.apt_repository:
    filename: mongodb
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/mongodb.asc]
      https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse
    state: present
  tags: *tags

- name: Install MongoDB
  ansible.builtin.apt:
    name: mongodb-org
    state: latest
  tags: *tags

- name: Start MongoDB daemon
  ansible.builtin.systemd:
    name: mongod
    state: started
  tags: *tags
