- name: Download node archive
  ansible.builtin.get_url:
    url: https://nodejs.org/dist/v19.0.0/node-v19.0.0-linux-x64.tar.gz
    dest: /tmp/node-v19.0.0.tar.gz
    owner: lixaft
    group: lixaft
    mode: "0755"
  tags: &tags
    - node

- name: Create node directory
  ansible.builtin.file:
    path: /home/lixaft/.opt/node-v19.0.0
    state: directory
    owner: lixaft
    group: lixaft
    mode: "0755"
  tags: *tags

- name: Unarchive node
  ansible.builtin.unarchive:
    src: /tmp/node-v19.0.0.tar.gz
    dest: /home/lixaft/.opt/
    owner: lixaft
    group: lixaft
    mode: "0755"
  tags: *tags

- name: Symlink node executables
  ansible.builtin.file:
    src: /home/lixaft/.opt/node-v19.0.0-linux-x64/bin/{{ item }}
    dest: /home/lixaft/.local/bin/{{ item }}
    state: link
    owner: lixaft
    group: lixaft
  loop:
    - node
    - npm
    - npx
    - corepack
  tags: *tags
