- name: Download virtualenv
  ansible.builtin.get_url:
    url: https://bootstrap.pypa.io/virtualenv.pyz
    dest: /tmp/virtualenv.pyz
    owner: lixaft
    group: lixaft
    mode: "0644"
  tags: &tags
    - pip
    - update

- name: Install python packages in a virtualenv
  become: true
  become_user: lixaft
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
    virtualenv: /home/lixaft/.opt/{{ item }}
    virtualenv_command: python3 /tmp/virtualenv.pyz
  loop: &packages
    - hatch
    - pre-commit
    - pytest
    - tox
    - twine
    - virtualenv
  tags: *tags

- name: Symlink executables from the virtualenv
  ansible.builtin.file:
    src: /home/lixaft/.opt/{{ item }}/bin/{{ item }}
    dest: /home/lixaft/.local/bin/{{ item }}
    state: link
    owner: lixaft
    group: lixaft
  loop: *packages
  tags: *tags
