- name: Install python
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - python2-dev
    - python3-dev
    - python3-distutils
    - python3-venv
  tags: &tags
    - python

- name: Add deadsnakes repository
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
  tags: *tags

- name: Install python from deadsnakes
  ansible.builtin.apt:
    name:
      - "{{ item }}-dev"
      - "{{ item }}-distutils"
    state: latest
  loop:
    - python3.7
    - python3.8
    - python3.9
    - python3.10
    - python3.11
    - python3.12
  tags: *tags

- name: Install pypy
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - pypy
    - pypy3
  tags: *tags
