- name: Check if rust is installed
  become: true
  become_user: lixaft
  ansible.builtin.command:
    cmd: which cargo
  register: check_cargo
  ignore_errors: true
  changed_when: false
  tags: &tags
    - rust

- name: Install rust
  when: check_cargo is failed
  block:
    - name: Download rustup
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        owner: lixaft
        group: lixaft
        mode: "0700"
      register: download_result
      tags: *tags

    - name: Execute rustup
      become: true
      become_user: lixaft
      ansible.builtin.command:
        cmd: /tmp/rustup.sh -y
      when: download_result is succeeded
      changed_when: true
      tags: *tags
