- name: Create ssh directory
  ansible.builtin.file:
    path: /home/lixaft/.ssh
    state: directory
    owner: lixaft
    group: lixaft
    mode: "0700"
  tags: &tags
    - ssh
    - dotfiles

- name: Copy ssh key
  ansible.builtin.copy:
    src: id_ed25519
    dest: /home/lixaft/.ssh/id_ed25519
    force: true
    owner: lixaft
    group: lixaft
    mode: "0600"
  tags: *tags

- name: Copy ssh public key
  ansible.builtin.copy:
    src: id_ed25519.pub
    dest: /home/lixaft/.ssh/id_ed25519.pub
    force: true
    owner: lixaft
    group: lixaft
    mode: "0644"
  tags: *tags
