- name: zig | Download archive
  ansible.builtin.get_url:
    url: https://ziglang.org/builds/zig-linux-x86_64-{{ zig_version }}.tar.xz
    dest: /tmp/zig-{{ zig_version }}.tar.xz
    owner: lixaft
    group: lixaft
    mode: "0755"

- name: zig | Create unarchive directory
  ansible.builtin.file:
    path: /tmp/zig-{{ zig_version }}
    state: directory
    owner: lixaft
    group: lixaft
    mode: "0755"

- name: zig | Unarchive
  ansible.builtin.unarchive:
    src: /tmp/zig-{{ zig_version }}.tar.xz
    dest: /tmp/zig-{{ zig_version }}
    owner: lixaft
    group: lixaft
    mode: "0755"

- name: zig | Create install directory
  ansible.builtin.file:
    path: /home/lixaft/.opt/zig
    state: directory
    owner: lixaft
    group: lixaft
    mode: "0755"

- name: zig | Move to install directory
  ansible.builtin.command:
    argv:
      - mv
      - /tmp/zig-{{ zig_version }}/zig-linux-x86_64-{{ zig_version }}
      - /home/lixaft/.opt/zig/{{ zig_version }}
    creates: /home/lixaft/.opt/zig/{{ zig_version }}

- name: zig | Symlink executables
  become: true
  become_user: lixaft
  ansible.builtin.file:
    src: /home/lixaft/.opt/zig/{{ zig_version }}/zig
    dest: /home/lixaft/.local/bin/{{ item }}
    state: link
    owner: lixaft
    group: lixaft
  loop:
    - zig
