---
galaxy_info:
  role_name: nvim
  author: Fabien Taxil

  description: >-
    Install neovim with the lazy plugin manager

  license: MIT
  min_ansible_version: "2.8"

  platforms:
    - name: macOS
      versions:
        - all

  galaxy_tags:
    - editor
    - terminal
    - vim

dependencies:
  - role: dotfiles
  - role: homebrew
    when: ansible_os_family == 'Darwin'
