- name: dotfiles | Clone repository
  become: true
  become_user: lixaft
  ansible.builtin.git:
    repo: git@github.com:lixaft/dotfiles
    dest: /home/lixaft/dotfiles
    update: false
    accept_newhostkey: true

- name: dotfiles | Create symlinks
  become: true
  become_user: lixaft
  ansible.builtin.command:
    cmd: stow -R home
    chdir: /home/lixaft/dotfiles
  changed_when: true

- name: dotfiles | Build bat cache
  become: true
  become_user: lixaft
  ansible.builtin.command:
    cmd: batcat cache --build
  changed_when: true
