---
galaxy_info:
  role_name: podman
  author: Fabien Taxil

  description: >-
    Install and setup podman

  license: MIT
  min_ansible_version: "2.8"

  platforms:
    - name: macOS
      versions:
        - all

  galaxy_tags:
    - container

dependencies:
  - role: homebrew
    when: ansible_os_family == 'Darwin'
