- name: apt | Download keys
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: /etc/apt/keyrings/{{ item.filename }}
    owner: root
    group: root
    mode: "0644"
  loop: "{{ data | dict2items(key_name='filename', value_name='url') }}"
  loop_control:
    label: "{{ item.filename }}"
  vars:
    data:
      1password.asc: https://downloads.1password.com/linux/keys/1password.asc
      anydesk.asc: https://keys.anydesk.com/repos/DEB-GPG-KEY
      brave-browser.gpg: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
      filebot.asc: https://raw.githubusercontent.com/filebot/plugins/master/gpg/maintainer.pub
      githubcli.gpg: https://cli.github.com/packages/githubcli-archive-keyring.gpg
      mongodb.asc: https://pgp.mongodb.com/server-7.0.asc
      postgresql.asc: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      spotify.asc: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg

- name: apt | Add repositories
  ansible.builtin.apt_repository:
    filename: "{{ item.filename }}"
    repo: "{{ item.repo }}"
    mode: "0644"
    state: present
    update_cache: false
  loop: "{{ data | dict2items(key_name='filename', value_name='repo') }}"
  loop_control:
    label: "{{ item.filename }}"
  vars:
    data:
      1password: >-
        deb [arch=amd64 signed-by=/etc/apt/keyrings/1password.asc]
        https://downloads.1password.com/linux/debian/amd64 stable main
      anydesk: >-
        deb [signed-by=/etc/apt/keyrings/anydesk.asc]
        http://deb.anydesk.com/ all main
      brave-browser:
        deb [arch=amd64 signed-by=/etc/apt/keyrings/brave-browser.gpg]
        https://brave-browser-apt-release.s3.brave.com/ stable main
      deadsnakes: >-
        ppa:deadsnakes/ppa
      filebot: >-
        deb [arch=all signed-by=/etc/apt/keyrings/filebot.asc]
        https://get.filebot.net/deb/ universal main
      fish: >-
        ppa:fish-shell/release-3
      githubcli: >-
        deb [arch=amd64 signed-by=/etc/apt/keyrings/githubcli.gpg]
        https://cli.github.com/packages stable main
      mongodb: >-
        deb [arch=amd64 signed-by=/etc/apt/keyrings/mongodb.asc]
        https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse
      neovim: >-
        ppa:neovim-ppa/unstable
      obs-studio: >-
        ppa:obsproject/obs-studio
      peek: >-
        ppa:peek-developers/stable
      postgresql: >-
        deb [arch=amd64 signed-by=/etc/apt/keyrings/postgresql.asc]
        https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
      qbittorrent: >-
        ppa:qbittorrent-team/qbittorrent-stable
      spotify: >-
        deb [arch=amd64 signed-by=/etc/apt/keyrings/spotify.asc]
        http://repository.spotify.com stable non-free

- name: apt | Update cache
  ansible.builtin.apt:
    update_cache: true
