- name: apt | Download keys
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: /etc/apt/keyrings/{{ item.filename }}
    owner: root
    group: root
    mode: "0644"
  loop: "{{ data | dict2items(key_name='filename', value_name='url') }}"
  loop_control:
    label: "{{ item.filename }}"
  vars:
    data:
      githubcli.gpg: https://cli.github.com/packages/githubcli-archive-keyring.gpg
      mongodb.asc: https://pgp.mongodb.com/server-7.0.asc
      postgresql.asc: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: apt | Add repositories
  ansible.builtin.apt_repository:
    filename: "{{ item.filename }}"
    repo: "{{ item.repo }}"
    mode: "0644"
    state: present
    update_cache: false
  loop: "{{ data | dict2items(key_name='filename', value_name='repo') }}"
  loop_control:
    label: "{{ item.filename }}"
  vars:
    data:
      deadsnakes: >-
        ppa:deadsnakes/ppa
      fish: >-
        ppa:fish-shell/release-3
      githubcli: >-
        deb [arch=amd64 signed-by=/etc/apt/keyrings/githubcli.gpg]
        https://cli.github.com/packages stable main
      mongodb: >-
        deb [arch=amd64 signed-by=/etc/apt/keyrings/mongodb.asc]
        https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse
      neovim: >-
        ppa:neovim-ppa/unstable
      postgresql:
        deb [arch=amd64 signed-by=/etc/apt/keyrings/postgresql.asc]
        https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main

- name: apt | Update cache
  ansible.builtin.apt:
    update_cache: true
