- name: APT tasks
  ansible.builtin.import_tasks:
    file: apt.yml
  tags: [apt]

- name: Flatpak tasks
  ansible.builtin.import_tasks:
    file: flatpak.yml
  tags: [flatpak]

- name: Nix tasks
  ansible.builtin.import_tasks:
    file: nix.yml
  tags: [nix]

- name: Sudo tasks
  ansible.builtin.import_tasks:
    file: sudo.yml
  tags: [sudo]
