---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - curl
    - fd-find
    - g++
    - gcc
    - git
    - ripgrep
    - software-properties-common
    - tree
    - wget
