- name: Install pavu control
  ansible.builtin.apt:
    name: pavucontrol
    state: latest
  tags: &tags
    - desktop
    - audio

- name: Install ALSA utilities
  ansible.builtin.apt:
    name:
      - amixer
      - alsamixer
    state: latest
  tags: *tags

- name: Install playerctl
  ansible.builtin.apt:
    name: playerctl
    state: latest
  tags: *tags
