- name: display_manager | Clone ly repository
  ansible.builtin.git:
    repo: https://github.com/fairyglade/ly
    dest: /tmp/ly
    update: true

- name: display_manager | Build ly
  ansible.builtin.shell:
    cmd: |
      make
      make install installsystemd
    args:
      chdir: /tmp/ly
      executable: /usr/bin/bash

- name: display_manager | Start ly daemon
  ansible.builtin.systemd:
    name: ly
    state: started
  # Does not work in container.
  ignore_errors: true
