- name: Create fonts directory
  ansible.builtin.file:
    path: /home/lixaft/.local/share/fonts
    state: directory
    owner: lixaft
    group: lixaft
    mode: "0755"
  tags: &tags
    - font
    - desktop

- name: Download nerd fonts
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/{{ item }}.zip
    dest: /tmp/{{ item }}.zip
    owner: lixaft
    group: lixaft
    mode: "0644"
  loop: &fonts
    - FiraCode
    - DejaVuSansMono
  tags: *tags

- name: Unarchive the fonts
  ansible.builtin.unarchive:
    src: /tmp/{{ item }}.zip
    dest: /home/lixaft/.local/share/fonts/{{ item }}
  loop: *fonts
  tags: *tags
