- name: Create the Bazecor directory
  ansible.builtin.file:
    path: /home/lixaft/.opt/bazecor/{{ bazecor_version }}
    state: directory
    owner: lixaft
    group: lixaft
    mode: "0755"
  tags: &tags
    - bazecor

- name: Download the bazecor app image
  ansible.builtin.get_url:
    url: https://github.com/Dygmalab/Bazecor/releases/download/bazecor-{{ bazecor_version }}/Bazecor-{{ bazecor_version }}-x64.AppImage
    dest: /home/lixaft/.opt/bazecor/{{ bazecor_version }}/bazecor
    owner: lixaft
    group: lixaft
    mode: "0755"
  tags: *tags

- name: Symlink bazecor executable
  become: true
  become_user: lixaft
  ansible.builtin.file:
    src: /home/lixaft/.opt/bazecor/{{ bazecor_version }}/bazecor
    dest: /home/lixaft/.local/bin/bazecor
    state: link
    owner: lixaft
    group: lixaft
  tags: *tags

- name: Copy desktop file
  ansible.builtin.copy:
    src: bazecor.desktop
    dest: /home/lixaft/.local/share/applications/bazecor.desktop
    force: true
    owner: lixaft
    group: lixaft
    mode: "0644"
  tags: *tags
