---
galaxy_info:
  role_name: pip
  author: Fabien Taxil

  description: >-
    Install pip python packages

  license: MIT
  min_ansible_version: "2.8"

  platforms:
    - name: macOS
      versions:
        - all

  galaxy_tags:
    - pip
    - python

dependencies:
  - role: python
